# Generated by Django 3.1 on 2020-08-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20200817_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='rules_JSON',
            field=models.TextField(blank=True, null=True),
        ),
    ]
