# Generated by Django 3.1 on 2020-08-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20200817_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournaments',
            old_name='rules_JSON',
            new_name='rules_json',
        ),
    ]
