# Generated by Django 3.1 on 2020-08-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20200817_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='rules_json',
        ),
    ]
