# Generated by Django 3.1 on 2020-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_remove_tournaments_rules_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='rules_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
