# Generated by Django 3.1 on 2020-08-20 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_auto_20200817_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubs',
            options={'verbose_name': 'Клуб', 'verbose_name_plural': 'Клубы'},
        ),
        migrations.AlterModelOptions(
            name='divisions',
            options={'verbose_name': 'Эшелон', 'verbose_name_plural': 'Эшелоны'},
        ),
        migrations.AlterModelOptions(
            name='fighters',
            options={'verbose_name': 'Боец', 'verbose_name_plural': 'Бойцы'},
        ),
        migrations.AlterModelOptions(
            name='tournamentfights',
            options={'verbose_name': 'Бой', 'verbose_name_plural': 'Бои'},
        ),
        migrations.AlterModelOptions(
            name='tournamentnominations',
            options={'verbose_name': 'Турнирная номинация', 'verbose_name_plural': 'Турнирные номинации'},
        ),
        migrations.AlterModelOptions(
            name='tournaments',
            options={'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.AlterModelOptions(
            name='weapons',
            options={'verbose_name': 'Класс оружия', 'verbose_name_plural': 'Классы оружия'},
        ),
        migrations.AddField(
            model_name='fighters',
            name='city',
            field=models.CharField(default='Астрахань', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fighters',
            name='current_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.clubs', verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='fighters',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='fighters',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='fighters',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='fighters',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
    ]
